### ISSUE TITLE
Add tooltips to browser bar UI

### ISSUE THREAD

**Issue by JadeMaveric** [JadeMaveric/patronus#6]
I tried to make the UI as intuitive as possible, and did initially add tooltips to the input labels. But my CSS skills aren't the best, and it messed up the layout.

I suppose this should be something fairly simple to anyone with frontend experience. Either to fix the CSS, or switch to using the title attribute (and removing the unnecessary CSS)

A suitable PR would add tooltips to the `keywords` and `interval` label documenting what they do.

**Comment by ameybh** [comment]
Hi. The `keyword` textarea already has a description. Do you want to remove that and add a tooltip or something else(like a placeholder)?

**Comment by ilkerunal** [comment]
Could you please assign this to me ?

**Comment by JadeMaveric** [comment]
@ameybhavsar24 You can leave the text in the `textarea` tag. It'll only show up on first use once #3 is implemented. But you can reuse the same text in the popup. Or use a summarized form of the description given in README.md

@ilkerunal Sorry, I'm going to assign on an FCFS basis
